### ISSUE TITLE
Typos in the README.md

### ISSUE THREAD

**Issue by matteoguarrera** [SqueezeAILab/SqueezeLLM#6]
In both *Benchmarking*
`CUDA_VISIBLE_DEVICES=0 python llama.py <path-to-llama-7b-hf> c4 --wbits 4 --load sq-llama-7b-w3-o0.pt --benchmark 128 --check`
and *Perplexity Evaluation* 
`CUDA_VISIBLE_DEVICES=0 python llama.py <path-to-llama-7b-hf> c4 --wbits 4 --load sq-llama-7b-w3-o0.pt --eval`
there is a typo in the name of the sq-llama. It should be **sq-llama-7b-w3-s0.pt** not *sq-llama-7b-w3-o0.pt*. 

The suggested flag **--wbits 4** doesn't match the pretrained checkpoint suggested that has been quantized at 3 bits. So it should be **--wbits 3**.
Great job!

**Comment by amirgholami** [comment]
Thanks for catching that Matteo! Should be fixed now.

**Comment by matteoguarrera** [comment]
The suggested flag *--wbits 4* for both commands is still wrong. It should be **--wbits 3**, since the checkpoint is **sq-llama-7b-w3-s0.pt**
